//
//  ModelConstants.swift
//  MyLive2D-SwiftUI
//
//  Created by HT Zhang  on 2024/12/05.
//

// パーツID
let HitAreaPrefix = "HitArea"
let HitAreaHead = "Head"
let HitAreaBody = "Body"
let PartsIdCore = "Parts01Core"
let PartsArmPrefix = "Parts01Arm_"
let PartsArmLPrefix = "Parts01ArmL_"
let PartsArmRPrefix = "Parts01ArmR_"

// パラメータID
let ParamAngleX = "ParamAngleX"
let ParamAngleY = "ParamAngleY"
let ParamAngleZ = "ParamAngleZ"
let ParamEyeLOpen = "ParamEyeLOpen"
let ParamEyeLSmile = "ParamEyeLSmile"
let ParamEyeROpen = "ParamEyeROpen"
let ParamEyeRSmile = "ParamEyeRSmile"
let ParamEyeBallX = "ParamEyeBallX"
let ParamEyeBallY = "ParamEyeBallY"
let ParamEyeBallForm = "ParamEyeBallForm"
let ParamBrowLY = "ParamBrowLY"
let ParamBrowRY = "ParamBrowRY"
let ParamBrowLX = "ParamBrowLX"
let ParamBrowRX = "ParamBrowRX"
let ParamBrowLAngle = "ParamBrowLAngle"
let ParamBrowRAngle = "ParamBrowRAngle"
let ParamBrowLForm = "ParamBrowLForm"
let ParamBrowRForm = "ParamBrowRForm"
let ParamMouthForm = "ParamMouthForm"
let ParamMouthOpenY = "ParamMouthOpenY"
let ParamCheek = "ParamCheek"
let ParamBodyAngleX = "ParamBodyAngleX"
let ParamBodyAngleY = "ParamBodyAngleY"
let ParamBodyAngleZ = "ParamBodyAngleZ"
let ParamBreath = "ParamBreath"
let ParamArmLA = "ParamArmLA"
let ParamArmRA = "ParamArmRA"
let ParamArmLB = "ParamArmLB"
let ParamArmRB = "ParamArmRB"
let ParamHandL = "ParamHandL"
let ParamHandR = "ParamHandR"
let ParamHairFront = "ParamHairFront"
let ParamHairSide = "ParamHairSide"
let ParamHairBack = "ParamHairBack"
let ParamHairFluffy = "ParamHairFluffy"
let ParamShoulderY = "ParamShoulderY"
let ParamBustX = "ParamBustX"
let ParamBustY = "ParamBustY"
let ParamBaseX = "ParamBaseX"
let ParamBaseY = "ParamBaseY"
let ParamNONE = "NONE:"
